name: ESP8266 RTOS SDK Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip cmake ninja-build ccache libffi-dev libssl-dev dfu-util unzip xz-utils

      - name: Install ESP8266 RTOS SDK
        run: |
          git clone --recursive https://github.com/espressif/ESP8266_RTOS_SDK.git $HOME/esp8266-rtos-sdk
          echo "IDF_PATH=$HOME/esp8266-rtos-sdk" >> $GITHUB_ENV
          export IDF_PATH=$HOME/esp8266-rtos-sdk
          python3 -m pip install --upgrade pip
          $IDF_PATH/install.sh

      - name: Build firmware
        run: |
          cd $GITHUB_WORKSPACE
          . $IDF_PATH/export.sh
          make

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.bin
